import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    /**
     * Placeholder catalog art is SVG (see scripts/generate-placeholders.mjs).
     * Next refuses to optimise SVG without this flag because a hostile SVG can
     * carry script. Everything served here is generated by us into `public/`,
     * and the CSP below sandboxes it regardless.
     *
     * When real product photography replaces the placeholders, this whole
     * block can go.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",

    /** Phone-first breakpoints — no point generating 3840px variants. */
    deviceSizes: [360, 414, 640, 828, 1080, 1280, 1600],
    imageSizes: [64, 96, 128, 180, 256, 384],
    formats: ["image/avif", "image/webp"],
    minimumCacheTTL: 60 * 60 * 24 * 30,
  },

  experimental: {
    /** Faster cold compiles across restarts during development. */
    turbopackFileSystemCacheForDev: true,
  },
};

export default nextConfig;
