#!/usr/bin/env bash
#
# gng — first-run setup on a fresh VPS.
#
#   bash deploy/bootstrap.sh
#
# Generates the secrets, writes .env, builds the images, creates the database
# schema, and creates the first admin account — then prints the password once.
#
# Safe to re-read: it refuses to overwrite an existing .env, so running it twice
# cannot silently rotate your secrets and lock you out of your own database.

set -euo pipefail

cd "$(dirname "$0")/.."

BOLD=$'\e[1m'; DIM=$'\e[2m'; GREEN=$'\e[32m'; RED=$'\e[31m'; YELLOW=$'\e[33m'; OFF=$'\e[0m'

step() { printf '\n%s==> %s%s\n' "$BOLD" "$1" "$OFF"; }
fail() { printf '%sError:%s %s\n' "$RED" "$OFF" "$1" >&2; exit 1; }

# --- Prerequisites ---------------------------------------------------------

step "Checking prerequisites"

command -v docker >/dev/null 2>&1 || fail "Docker is not installed. See https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || fail "The Docker Compose plugin is missing. Install docker-compose-plugin."
docker info >/dev/null 2>&1 || fail "Cannot talk to the Docker daemon. Try: sudo systemctl start docker"

printf '%s  Docker and Compose are ready.%s\n' "$DIM" "$OFF"

# --- Secrets ---------------------------------------------------------------
# openssl is present on every mainstream server image; falling back to
# /dev/urandom keeps this working on a minimal one.

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n=+/' | cut -c1-48
  else
    head -c 96 /dev/urandom | base64 | tr -d '\n=+/' | cut -c1-48
  fi
}

if [ -f .env ]; then
  step "Using the existing .env"
  printf '%s  Left untouched. Delete it first if you want to start over.%s\n' "$DIM" "$OFF"
else
  step "Creating .env"

  # The two public URLs are the only things a person has to decide.
  read -rp "Storefront domain (e.g. gng.com.bd): " SITE_DOMAIN
  [ -n "$SITE_DOMAIN" ] || fail "A domain is required."

  read -rp "API subdomain [api.${SITE_DOMAIN}]: " API_DOMAIN
  API_DOMAIN="${API_DOMAIN:-api.${SITE_DOMAIN}}"

  read -rp "Your admin email [owner@${SITE_DOMAIN}]: " ADMIN_EMAIL
  ADMIN_EMAIL="${ADMIN_EMAIL:-owner@${SITE_DOMAIN}}"

  read -rp "WhatsApp number, digits with country code [8801700000000]: " WHATSAPP
  WHATSAPP="${WHATSAPP:-8801700000000}"

  read -rp "Hotline shown in the footer [09612000000]: " HOTLINE
  HOTLINE="${HOTLINE:-09612000000}"

  POSTGRES_PASSWORD="$(random_secret)"
  JWT_ACCESS_SECRET="$(random_secret)"
  # Left blank on purpose: the seeder generates a strong one and prints it once,
  # which is better than a password that also sits in a file on the server.
  cat > .env <<ENVFILE
# Generated by deploy/bootstrap.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# Keep this file private. It is gitignored.

SITE_URL=https://${SITE_DOMAIN}
API_PUBLIC_URL=https://${API_DOMAIN}

POSTGRES_USER=gng
POSTGRES_DB=gng
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
COOKIE_SECURE=true
COOKIE_DOMAIN=

TRUST_PROXY_HOPS=1
LOG_LEVEL=info

SEED_ADMIN_EMAIL=${ADMIN_EMAIL}
SEED_ADMIN_PASSWORD=
SEED_ADMIN_NAME=Owner

NEXT_PUBLIC_WHATSAPP_NUMBER=${WHATSAPP}
NEXT_PUBLIC_HOTLINE=${HOTLINE}
ENVFILE

  chmod 600 .env
  printf '%s  Secrets generated. .env is readable only by you (chmod 600).%s\n' "$DIM" "$OFF"
fi

# --- Build and start -------------------------------------------------------

step "Building images (first run takes a few minutes)"
docker compose build

step "Starting Postgres, the API and the storefront"
docker compose up -d

step "Waiting for the database"
# Compose already gates the API on the healthcheck; this is just so the
# migration below does not race a database that is still initialising.
for _ in $(seq 1 60); do
  if docker compose exec -T postgres pg_isready -U gng -d gng >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
docker compose exec -T postgres pg_isready -U gng -d gng >/dev/null 2>&1 \
  || fail "Postgres did not come up. Check: docker compose logs postgres"

step "Creating the database schema"
# `:prod` runs the COMPILED entrypoint. The runtime image is pruned with
# `npm prune --omit=dev`, so `tsx` — and the TypeScript source it would run —
# are both absent from it. Calling the dev script here fails with
# `sh: tsx: not found` after everything else has already succeeded.
docker compose exec -T api npm run db:migrate:prod

step "Creating your admin account"
# The seeder is idempotent: on a re-run against a database that already has an
# admin it prints "Skipped" and changes nothing.
SEED_OUTPUT="$(docker compose exec -T api npm run db:seed:prod 2>&1)"
echo "$SEED_OUTPUT" | grep -vE '^\s*$|^>' || true

# --- Done ------------------------------------------------------------------

ADMIN_PASSWORD="$(printf '%s' "$SEED_OUTPUT" | sed -n 's/.*Generated password: *//p' | tr -d '\r')"

printf '\n%s============================================================%s\n' "$GREEN" "$OFF"
printf '%s  gng is running.%s\n' "$GREEN$BOLD" "$OFF"
printf '%s============================================================%s\n\n' "$GREEN" "$OFF"

if [ -n "$ADMIN_PASSWORD" ]; then
  printf '  %sAdmin sign-in%s\n' "$BOLD" "$OFF"
  printf '    URL:      https://%s/admin/login\n' "$SITE_DOMAIN"
  printf '    Email:    %s\n' "${ADMIN_EMAIL:-see SEED_ADMIN_EMAIL in .env}"
  printf '    Password: %s%s%s\n\n' "$BOLD" "$ADMIN_PASSWORD" "$OFF"
  printf '  %sWrite the password down now. It is not stored anywhere and\n' "$YELLOW"
  printf '  will not be shown again.%s\n\n' "$OFF"
else
  printf '  An admin account already existed, so no new password was created.\n\n'
fi

printf '  %sNext:%s point DNS at this server and set up HTTPS —\n' "$BOLD" "$OFF"
printf '  see deploy/Caddyfile.example and deploy/README.md.\n\n'
printf '  The shop starts with %szero products%s. Add yours at /admin/products.\n\n' "$BOLD" "$OFF"
